### ISSUE TITLE
appeal of chatgpt.rbqwow.cf and other domains like this

### ISSUE THREAD

**Issue by Rbqwow** [RPiList/specials#1026]
In some countries like China, people can't access to ChatGPT and its API directly. But we can use CloudFlare Workers and a domain name to bypass the API limitation such as [this](https://github.com/x-dr/chatgptProxyAPI) repo.
These domains are usually used by private and not the so-called malware domain. They just allow people from countries that don't have access to the ChatGPT API to be able to connect.
So, please remove these domains from the malware list. Thanks.

**Comment by RPiList** [comment]
Hi,
thx for clearing this up. The Problem is that we can not see the difference between the course you mentioned and the usual phishing site trying to scam people.

But: Us blocking these sites will only result in a problem for users in China, IF they use our blocking list. From what I see, we don't have users from China...

**Comment by Rbqwow** [comment]
hmm
I just searched myself on Google and found this. You know, it's uncomfortable being told "you're spreading malware" by other people when u actually don't.
So...Could u plz only remove my domain from it?
If I'm causing trouble for ur automatic update, I'd change the domain right away.
Thanks again 😶
