### ISSUE TITLE
Bei mir lief heute morgen fast nix mehr

### ISSUE THREAD

**Issue by Rikkert-RS** [RPiList/specials#1110]
Also durch die "GAMBLING" Liste lief bei mir heute fast nix mehr. Da sind viele Domains falsch.

z.B. WetterOnline.de wie kommt das denn da rein? 
Die Liste ist auch von der Datenmenge von vor 2 Tage um die häfte geschrumpft, ich glaube da ist ordentlich was falsch gelaufen. Der Apple App Store war auch nicht mehr zu erreichen.

mfg Rikkert-RS

**Comment by BulldozerPete** [comment]
Apple Services wie iPhone Update und Appstore sind auch blockiert.

**Comment by lukas-fichtner** [comment]
ja irgendwas ist da schief gelaufen :D

**Comment by haruzept** [comment]
Kann ich bestätigen. Tagesschau.de etc. funktionieren auch nicht mehr.
"www.tagesschau.de.edgekey.net ->
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/gambling:
  ||edgekey.net^"

**Comment by Rikkert-RS** [comment]
Ist bei mir aber nur diese eine Liste die alles blockiert hat, habe ich nun kurzzeitig mal deaktiviert.

**Comment by ucsbricks** [comment]
Mir fiel heute zuerst auf, dass alle(?) großen deutschen Medienseiten nicht mehr aufrufbar sind, aber das liegt nicht nur an der „gambling“ Liste. Ein Beispiel: rp-online.de ist durch die Listen „gambling“ und „pornblock1“ gesperrt. Ist da kolossal etwas schief gelaufen oder handelt es sich um Sabotage?

---

The first thing I noticed today is that all(?) major German media sites are no longer accessible, but that's not just because of the "gambling" list. One example: rp-online.de is blocked by the "gambling" and the "pornblock1" list. Has something gone colossally wrong there, or is it sabotage?

**Comment by lukas-fichtner** [comment]
ja ist ist wohl nicht nur die gambling Liste betroffen

**Comment by ucsbricks** [comment]
Anscheinend sind auch österreichische Medien betroffen, siehe PR #1111 und #1112.

**Comment by ucsbricks** [comment]
Es gibt einen Sammelthread unter https://github.com/RPiList/specials/issues/1101 bitte dort posten.

**Comment by Rikkert-RS** [comment]
OK weiter gehts hier: https://github.com/RPiList/specials/issues/1101
