### ISSUE TITLE
ITCH.IO

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#1150]
Auf diese Seite kann man seine Games veröffendlichen leider gibt es da auch viele die Viren hochladen oder eine geklaute Games von Steam oder Epic

**Comment by RPiList** [comment]
Vielen Dank für die Diskussion. Genau das brauche ich, da ich die Plattform nicht kenne und auch nicht bei jedem Eintrag prüfen kann.

Ist die Plattform als "Indie Plattform" gestartet die "nur" auch missbraucht wird? Oder ist sie vom Layout und Umfang eher auf "Dummenfang" aus?

Vom Look'n'Feel her sieht die Seite absolut legitim aus. @SGirl-Zockt hast Du einen Link für den Virus-Vorwurf oder dass da geklaute Steam-Spiele zu finden sind?

**Comment by JeGr** [comment]
> Ist die Plattform als "Indie Plattform" gestartet die "nur" auch missbraucht wird? Oder ist sie vom Layout und Umfang eher auf "Dummenfang" aus?

AFAIR ist die Plattform als genau das gestartet und wird auch immer noch so genutzt. Viele Entwickler, die später u.a. bei Steam landen, haben auch mal anfänglich ihre Prototypen oder ersten Entwürfe auf itch.io veröffentlicht. 

Die Community Guidelines (https://itch.io/docs/general/community-rules) sowie die TOS (https://itch.io/docs/legal/terms) sind da auch recht eindeutig, dass Raubkopien oder Viren nicht erlaubt sind.

Die Plattform ist gerade wegen des Indie Backgrounds (bspw. Hosting a GameJam: https://itch.io/docs/creators/game-jams) bekannt und wird wie gesagt dafür auch häufig von offiziellen Events wie dem Ludum Dare GameJam (in 72h ein fertiges Spiel abliefern) etc. genutzt.

Vielleicht wurden hier auf "geklaute Games" verwechselt mit Prototypen? Beispiel aus der jüngeren Zeit. Terra Nil - wurde von Devolver Digital published und ist u.a. auf Steam, Epic und in Netflix Gaming enthalten. Tolles Spiel. Prototyp kam und ist noch auf itch.io einfach um die Herkunft und die Entwicklung zu zeigen: https://vfqd.itch.io/terra-nil vs. https://devolverdigital.itch.io/terra-nil

Vielleicht gibts wie so oft schwarze Schafe, dagegen wird aber soweit mir bekannt auch recht gut vorgegangen.

Cheers

**Comment by RPiList** [comment]
Dann hat sich das hier ja erledigt. Vielen Dank für die Infos. Viele Grüße

**Comment by SGirl-Zockt** [comment]
https://youtu.be/eUISCx4pEDw
Min 3:40 ca

**Comment by JeGr** [comment]
Das war wohl eine hochgeladene Kopie von Getting Over it. Nur dass bei 3:40 selbst der Youtuber einblendet, dass die Spiel-Seite von itch.io kurz danach gesperrt und gelöscht wurde. Eine Diskussion dazu gab es schonmal: https://itch.io/t/1560429/malware-on-itchio-has-anything-been-improved-on-this-since-couple-years-back

Wenn man anfängt deshalb Itch zu sperren, ist Steam ggf. das Nächste wie sich aus den Kommentaren aus obigem Link lesen lässt, denn selbst Steam hat mit solchen Copycat oder Kopie Problemen zu kämpfen. Oder auch mit Malware/Cryptominern:
https://www.digitaltrends.com/gaming/steam-game-allegedly-mining-cryptocurrency/

Cheers
