### ISSUE TITLE
Amazon App wont connect

### ISSUE THREAD

**Issue by SmarterHome33** [RPiList/specials#1223]
I've researched a little and it seems your list is blocking the Amazon App.

I am getting this address blocked: d3ag4hukkh62yn.cloudfront.net

And when I ran it through this command:
pihole -q -exact d3ag4hukkh62yn.cloudfront.net

It came back with:
https://v.firebog.net/hosts/RPiList-Phishing.txt

When I disable the RPiList-Phishing.txt item on my pihole, the app connects again.

I don't know how to fix it but I hope this information is helpful 😀

**Comment by SmarterHome33** [comment]
The website says it was updated 8/7 which is when is stopped working

# Updated 07AUG23 from https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe

I can't read the language in that link though

**Comment by RPiList** [comment]
> It came back with: https://v.firebog.net/hosts/RPiList-Phishing.txt

Hi,

this issue was fixed 4 days ago on the original list.

But according to your link, you are using a mirror-copy of the original list. But firebog stated that the problem should be fixed on his side too.

Please update your lists. If it still persists consider switching to the orginal list. Greetings.
