### ISSUE TITLE
https://v.firebog.net/hosts/RPiList-Malware.txt - remove 'drive.usercontent.google.com' as this is INCORRECTLY black listed

### ISSUE THREAD

**Issue by thechrisgregory** [RPiList/specials#1403]
Please remove the URL  'drive.usercontent.google.com' from 'RPiList-Malware.txt'.

Blacklistng this URL results in downloads from the Google Drive web interface failing with a 'HTTP error ' 
It is incorrectly blacklisted.

I have temporarily whitelisted this URL in my pihole config and it now works properly.

Thank you.

**Comment by SGirl-Zockt** [comment]
Hey,


Do you update your Blocklists in the Pihole?
My Pihole Say: [i] No results found for drive.usercontent.google.com within the adlists (i use alle list from Rpilist and from firebog.net

Go to the Webinterface then Tools and make a Update Gravity

**Comment by thechrisgregory** [comment]
Yes, I update them regularly, just checked/updated right now, and I must have missed this update to my gravity lists. OK to close this issue.

**Comment by SGirl-Zockt** [comment]
Happy New Year :)

**Comment by RPiList** [comment]
Firebog.net has a latency updating our lists, since he is not linking our list, he is copying it. So there always might be the possibility that we already deleted an entry, which his copy still caries.

I can't remember deleting drive.usercontent.google.com recently, and you pihole should auto update each sunday...

so this is strange...

**Comment by thechrisgregory** [comment]
Yeah – Happy New year!

**Comment by thechrisgregory** [comment]
I updated my adlists manually in the middle of the week, not sure exactly when, but it wasn’t a Sunday…..
