### ISSUE TITLE
False-Positive srf.ch

### ISSUE THREAD

**Issue by netranger512** [RPiList/specials#1423]
Good day

```
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe:
  backup.data.srf.ch
  data.srf.ch
  foro.data.srf.ch
  google.data.srf.ch
  lax.data.srf.ch
  nov.data.srf.ch
  s5.data.srf.ch
  stage.www.data.srf.ch
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware:
  ||backup.data.srf.ch^
  ||data.srf.ch^
  ||foro.data.srf.ch^
  ||google.data.srf.ch^
  ||lax.data.srf.ch^
  ||nov.data.srf.ch^
  ||s5.data.srf.ch^
  ||stage.www.data.srf.ch^
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails:
  ||data.srf.ch^
```

I am not sure what the subdomains are exactly used for but srf.ch is the swiss national television, so definitely not phishing nor malware. I recommend to remove it or move it to other lists. Is there any info how this made it into the list?

Cheers and thanks a lot

**Comment by RPiList** [comment]
These domains are all disguised tracking domains. Tracking services hidden, by using the srf.ch domain.

Domains will be deleted on the list "Phishing" and spam.mails because these domains are not phishing or spam.

But the domains will have to stay on the malware list since tracking is considered to be kind of malware. 

Greetings and thx for pointing it out.
