### ISSUE TITLE
False Positive: vishay.com on Malware List

### ISSUE THREAD

**Issue by Salvoxia** [RPiList/specials#1437]
Hi,

https://github.com/RPiList/specials/blob/master/Blocklisten/malware contains
`||vishay.com^`
which is a multinational semiconductor corporation. Please remove.

Best Regard,
Salvoxia

**Comment by RPiList** [comment]
Hi,

vishay.com has been marked as distributing malware by urlhaus.abuse.ch.

So I am afraid they have to stay on the list. Greetings

**Comment by marsfan** [comment]
@RPiList Seems strange that the documentation page for a multinational semiconductor company that has been around since 1962 to be marked as a distributor of viruses. I've filed a report on urlhaus.abuse.ch saying this is likely a false positive. If that report goes though, will it be automatically removed from the list? 

<details>
<summary>Translated By Computer To German</summary>

Es scheint seltsam, dass die Dokumentationsseite eines multinationalen Halbleiterunternehmens, das es seit 1962 gibt, als Virenverteiler markiert wird. Ich habe einen Bericht auf urlhaus.abuse.ch eingereicht, der besagt, dass es sich wahrscheinlich um einen Fehlalarm handelt. Wird die Seite automatisch aus der Liste entfernt, wenn die Meldung angenommen wird? 
</details>
