### ISSUE TITLE
False positive pafms.ocbc.com

### ISSUE THREAD

**Issue by bounzqueen** [RPiList/specials#1450]
False positive pafms.ocbc.com in [https://v.firebog.net/hosts/RPiList-Phishing.txt](https://v.firebog.net/hosts/RPiList-Phishing.txt) under Phishing List.

ocbc.com is my bank's domain and I'm unable to login to internet banking with this domain blocked.

**Comment by RPiList** [comment]
Hi,
thx for supporting us.

pafms.ocbc.com and
uafms.ocbc.com

have been flaged as tracking domains by the Adguard Team.

Thats why I removed them from Pishing because Tracking is not some kind of phishing. But the domains will end up in a lot of malware lists because Tracking is considered to be some kind of malware.

Greetings.
