### ISSUE TITLE
false positive web page - *.avaya.com

### ISSUE THREAD

**Issue by darkmanlv** [RPiList/specials#1453]
please remove *.avaya.com from lists, it is false positive, it is company avaya web sites for partners, support, etc.

https://v.firebog.net/hosts/RPiList-Malware.txt
https://v.firebog.net/hosts/RPiList-Phishing.txt

**Comment by RPiList** [comment]
Hi,
thx for contacting us. Domains have been removed from the phishing list.

But these domains are flagged as tracking (disguised-microsites and disguised-tracking) by the Adguard-Team. Domains in our list get automatically removed, when the Adguard-Team removes the flagging.

Usually, tracking is considered to be a kind of malware.

Maybe we should create a seperate tracking-list...

**Comment by LizenzFass78851** [comment]
@darkmanlv 
try to create this issue at https://github.com/AdguardTeam/cname-trackers/issues as that is one of the source lists used for the malware list (as @RPiList mentioned). Perhaps the false positive aspect will be taken into account there and the avaya.com domains will be removed directly from their lists, so that this change will also be reflected in the @RPiList lists and therefore in the firebog lists

**Comment by LizenzFass78851** [comment]
@RPiList 
I believe the domain mentioned will not be removed from the adguard lists because I have read on other issues that these cname lists are created automatically without having to take a white list into account when creating them. And for some issues it is stated that such tracker lists should not be used as a block list per se.

**What I mean by that** is that you might be able to remove the domain mentioned from the malware list, despite the fact that it can still be found on the adguard lists.  Otherwise the issue will persist longer.

**Comment by RPiList** [comment]
@LizenzFass78851 

The point is, that a CNAME Domain is used to hide a third party domain which does the tracking.

This might be over explaining (Mensplaining?? :-) but I try to clear it up for others who might not be as familiar with this.

Tracker uses for example avaya.tracker.com... but thats to obvious, so avaya.com creates abc.avaya.com to hide avaya.tracker.com

But it's still tracking and thus malware. 

Since all tracking is happening by the third party, is can't break any functionality on the main domain.

There are only two acceptions to this:
1. There is no breaking, but the site detects the blocking and is just complaining... or
2. It really breaks the site, but then it's most likely not even tracking. Because there can't be real functioning code for website A on a different server.

From what I can see is, that the webpage is working fine, with the blocked domains.

That brings us to two options. Outsource the tracker to a standalone list (we already had this, when we started to project) or leave the domains in until someone states which part of the website is not working...

Greetings.

**Comment by LizenzFass78851** [comment]
I think separating the tracking domains from the malware list to put it in a dedicated tracking list would be a good idea.  (if reasonable).

As for the blocked subdomains of the mentioned domain.  Some of the subdomains may be self-hosted services from avaya.com as the domain mentioned operates consulting services, among other things.

**Comment by RPiList** [comment]
> I think separating the tracking domains from the malware list to put it in a dedicated tracking list would be a good idea. (if reasonable).

We had this when we started 4 years ago. We merged them because everybody said we should and said that cname tracking is malware. So seperating would be a step back. Not sure how many cases we had, where blocking a cname domain also broke a website.

> 
> As for the blocked subdomains of the mentioned domain. Some of the subdomains may be self-hosted services from avaya.com as the domain mentioned operates consulting services, among other things.

In this case, it would not be a problematic cname domain. It would be just a regular subdomain. The guys over at Adguard don't add entries to their list easily. They checked the domains (when finding them) and saw that it leads to a different server which is for tracking.

Further: @darkmanlv didn't state, that the blocking is breaking the website. He just stated that the avaya.com website is "legit". Of course nobody is disputing. We habe tons of legit domains in our malware list, only blocking certain tracking subdomains. Malware is not only about having a malware.exe in your root-directory.
