### ISSUE TITLE
oe24.at still on spamlist

### ISSUE THREAD

**Issue by oe3gwu** [RPiList/specials#1619]
You still block the site. Update didnt help.

![grafik](https://github.com/RPiList/specials/assets/17622063/1d95990c-dcf1-43af-8f83-094128b819b6)

**Comment by RPiList** [comment]
No we do not.

oe24.at was never on the spamlist. It was on the child-protection list, where it got removed by your last issue. 

To take effekt you need to update your pihole lists. It is removed on our list.

The domain "data-d543661da8.oe24.at" is on the malware list, because it is malicious. So it has to stay on the malware list.  oe24.at is not blocked.

Greetings.
