### ISSUE TITLE
False positive - sg-payment.cydf.hoyoverse.com

### ISSUE THREAD

**Issue by sefinek** [RPiList/specials#1846]
https://raw.githubusercontent.com/RPiList/specials/refs/heads/master/Blocklisten/malware
This is not malware.

**Comment by RPiList** [comment]
Yes it is.
According to the Adgruad-Team its a combined disguised tracker.  Greetings.

**Comment by sefinek** [comment]
Maybe it would be better if you checked it yourself rather than relying solely on someone else's findings?
Your list is the only one blocking this; I have over 100 of them in my repository (:
By the way, if you consider this a tracker, why is it on the malware list?

![{4F158B2C-2958-4E4C-970D-3E9BB4EBD16B}](https://github.com/user-attachments/assets/237eaaed-4f85-4e80-9e16-3f0d5990e28a)

**Comment by RPiList** [comment]
Tracking is considered malware. 

Further: Blocking tracking domains usually doesn't break the website. That's because the tracking is done by third parties which have nothing to do with the function of said website. 

When the Adguard Team says it's tracking it is tracking. When they removed it, it gets automatically deleted from our list as well.
