### ISSUE TITLE
ipv4.login.msa.akadns6.net

### ISSUE THREAD

**Issue by zkxwpdam** [RPiList/specials#195]
Which imbecile is maintaining your blocklist BS over here?! Or do you carelessly add anything sent to you?

[Phishing-Angriffe](https://github.com/RPiList/specials/blob/d326d0f33b9f82d1660aa4e8deee551d26135a21/Blocklisten/Phishing-Angriffe)
`L76942 ipv4.login.msa.akadns6.net`
block requests on https://login.live.com which is e.g. needed for web.skype.com login

You blocklists are completely worthless if they have to be disabled because of false positives all the time 😡

**Comment by RPiList** [comment]
> Which imbecile is maintaining your blocklist BS over here?! Or do you carelessly add anything sent to you?

I guess that would be me. And yes, everything that is reported as used in a phishing-incident is beeing added to the list.

> 
> [Phishing-Angriffe](https://github.com/RPiList/specials/blob/d326d0f33b9f82d1660aa4e8deee551d26135a21/Blocklisten/Phishing-Angriffe)
> `L76942 ipv4.login.msa.akadns6.net`
> block requests on https://login.live.com which is e.g. needed for web.skype.com login

In that case shoud Microsoft or Skype to a better job and announce the domain as to be essential, as they did for the other domains you can find in our "Internet-Services" directory. Because we and many other blocklists import their domains from openphish.com and phishstats.info.

So if you don't like our list, feel free to add other lists. They will have the same problem, but who cares.

> You blocklists are completely worthless if they have to be disabled because of false positives all the time

Thank you for taking your time and mentioning it.  We have already whitelisted almost 60 domains used by various Microsoft services (s. https://github.com/RPiList/specials/blob/master/Internet%20Services/Microsoft ). But as I already said. If they dont tell the community which domains are important, this will happen all the time. Because these domains are beeing used in phishing attacks. So they didn't care too.

**Comment by zkxwpdam** [comment]
😞  I see the problem here. Sadly, it seem there is not much that can be done.
Anyways, thanks for trying to keep up 👍
