### ISSUE TITLE
why is my domain in your list?

### ISSUE THREAD

**Issue by luvi** [RPiList/specials#279]
Hello,

I am just wondering why caricovidmap.com is listed in your corona blocklist? Are you mass adding domains that have "covid" in it?

The map does not fall under any of these categories -> "fake shops, advertising, tracking and other attacks from the Internet"

**Comment by RPiList** [comment]
Hi,

yes, since 95% of all newly registered covid or corona domains are
fake-domains, we list them all. A "corona" or "covid" in a subdomain only,
would not have triggered our list.

Your domain has been deleted and our github list has been updated.

Thanks for sending us a message.

Greetings.



Am Di., 5. Mai 2020 um 17:46 Uhr schrieb Janique-ka John <
notifications@github.com>:
