### ISSUE TITLE
Coronacurve.info

### ISSUE THREAD

**Issue by dan-online** [RPiList/specials#387]
Hi,

I'd like to request that my domain "coronacurve.info" be taken off the coronavirus block list. I use John Hopkins data and I don't have any ads. I am quite confused about why it is on there and any information would be quite helpful!

Thanks

Dan

**Comment by RPiList** [comment]
The Corona-Blocklist contains almost 300.000 domains having "corona", "covid" and a few other triggers in their domain, not sub-domain.

Those are domains registered since the corona outbreak and most likely be phishing, malware, fake-news or other bad players.

For example: The german authority on covid is found on rki.de. So because of covid the are registered covid.rki.de or corona.rki.de. Those domains are not catched.

But Covid19-cure-now.com is catched.

Of course there are a few domains, blocked without cause. But these will be deleted after manual review, when reported.

Your domain has been deleted. Greetings.
