### ISSUE TITLE
Avoid spaces in blocklist file names

### ISSUE THREAD

**Issue by CodingSpiderFox** [RPiList/specials#404]
When parsing URLs, whitespaces can cause trouble.
Thus, I would change file names like https://github.com/RPiList/specials/blob/master/Internet%20Services/Amazon%20Video to https://github.com/RPiList/specials/blob/master/Internet%20Services/Amazon-Video

**Comment by H4ckZ** [comment]
PR #405 created.

**Comment by RPiList** [comment]
Thank you for your issue. 

When these lists were created, they were not intented to be used as blocklists. These are more like "whitelistings" that can not be imported by pi-hole. So they have to be copy & pasted. Thats why the filesnames have spaces.

But I guess renaming would not hurt anyone so that should not be a problem. Greetings and thx.
