### ISSUE TITLE
False Positive - hopin.com

### ISSUE THREAD

**Issue by f0o** [RPiList/specials#663]
hopin.com & www.hopin.com is listed under https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe

What's the rationale for that?

**Comment by RPiList** [comment]
Rationale should be obvious since they are listed in the Phishing-List.

What the problem was, is not so easy to see, since all source sites don't nessesarily list a reason for listing a domain. So it could be a stupid XSS flaw in a textbox. 

More important is, that the site is not listed anymore so it can be removed. thanks for your info.
