### ISSUE TITLE
storage.yandexcloud.net in Phishing-Angriffe

### ISSUE THREAD

**Issue by ShiGhost** [RPiList/specials#766]
The site storage.yandexcloud.net blacklisted by Phishing-Angriffe is not malicious.

**Comment by RPiList** [comment]
Yes it is.

Phish-Stats is listing 37 attacks on this domain right know.

![Unbenannt](https://user-images.githubusercontent.com/56664851/172004002-d44199ca-dcf5-4c13-8f31-d07975397aa2.PNG)

**Comment by RPiList** [comment]
Wow... that raises serious questions for sure.

WTF are images from mybox.ru doing on the same sub-domain as the phishing attacks? Are they being hacked or do they just don't care.

Now you have two options; given you don't want to switch to a service who actually cares. Because at this state mybox.ru says "if you wann use us, you have to allow pfishing...."

1: whitelist yandexcloud on your pihole and allow phishing or
2: delete every phishing-blocklist in your pi-hole because ours is not the only phishing-list using phish-stats as data source.
