### ISSUE TITLE
False positive: www.smbc.co.jp

### ISSUE THREAD

**Issue by mah-jp** [RPiList/specials#812]
www.smbc.co.jp is a false positive.

This domain is used by a legitimate Japanese bank.
Please remove this domain from the list (RPiList-Phishing.txt).

**Comment by RPiList** [comment]
Hi,

the domain you mentioned is currently not on any of our lists.

If you are sure that it was on one of our lists, it might have been automatically removed by the last update. Our 'malware' list removes domains, when the threat is no longer present. 

Please update your Pi-hole lists manually. Otherwise it will be updated next sunday.

Greetings

**Comment by RPiList** [comment]
Sorry... checked the wrong directory... it is indeed on our phishing list. Will check if it can be removed or it has to stay on the list. Greetings.

**Comment by RPiList** [comment]
Thx for letting us know. Domain has been removed. Greetings
