### ISSUE TITLE
analytics.twitter.com

### ISSUE THREAD

**Issue by SGirl-Zockt** [RPiList/specials#887]
Please Remove the Domian from your List
Exact matches for analytics.twitter.com found in:
 - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/easylist
 - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock1

LG

**Comment by RPiList** [comment]
Hi,
did you encounter any disruptions while using our lists? Analytics is tracking and often blocked.

Of course it will be removed from our pornlist. 

Greetings

**Comment by SGirl-Zockt** [comment]
Hello,

analytics.twitter.com is like t.co to open external Link in Twitter.

Nice Day

**Comment by RPiList** [comment]
Using an analytics subdomain as a link-shortener is highly unlikely. Analytics is more likely to be a tracking subdomain. 
As already mentioned, we have removed the domain from our pornlist since it is no porn. But the easylist is for tracking and is pulled from various third-party sources.

I am using the list myself and I am not experiencing any problems.

Greetings.

**Comment by SGirl-Zockt** [comment]
Hey,

Tell this please Twitter, Twitter use this for a long time

LG
