### ISSUE TITLE
False positive: users.atw.hu

### ISSUE THREAD

**Issue by MicrosoftEggshell** [RPiList/specials#977]
Hi, `users.atw.hu` is a site hosting content from many users (of [atw.hu](https://atw.hu)). Some may contain malware, but that's applicable to any site hosting user content. It isn't a malicious site on its own (lots of legitimate content), and should be removed from the malware blocklist. Thanks!

**Comment by RPiList** [comment]
Hi,
currently we have 230 subdomains (of users) from atw.com on our blocklists... mostly porn. But from what I can gather, user.atw.hu is not a subdomain from atw.hu itself, but just another subdomain a user from atw.hu is using. The html-code from that site is suggesting, its just a private user using that subdomain.

Can you elaborate on this? Because if its a user domain, it looks like he had malware on his site.

We are currently checking on which service reported the domain and trying to determine if it is a gone problem or if it still exists.

Greetings
