### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by kb-elmo** [RPiList/specials#980]
shared.jodel.com is currently in the malware list.

The domain is only used by the social networking app Jodel.
https://www.jodel.com

It's unlikely that it can spread any malware since it's only used internally by the app to share posts.

**Comment by RPiList** [comment]
Hi,
thx for letting us know. Jodel.com is being reported for reasons of tracking, by the Adguard Team. Since tracking is considered as a form of malware, I'm afraid it has to stay on the list until it is unlisted by Adguard.

If you need the domain, you could whitelist it on your pihole. 

Greetings.
