### ISSUE TITLE
Lists offline

### ISSUE THREAD

**Issue by mchawk777** [RPiList/specials#995]
Hi anybody,

these lists from **hagezi** seem to be offline:
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/doh-vpn-proxy-bypass.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/fake.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/nosafesearch.txt

He's not complete offline, this one works:
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/light.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/tif.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/multi.txt

**Comment by hagezi** [comment]
@mchawk777

For lists that did not contain subdomains and therefore did not make sense for Pi-hole because wildcard blocking was not supported, I discontinued support for domain/host-only lists. Since Pi-hole finally supports the AdBlock format as of FTL version 5.22, you can use this format instead.

See README: https://github.com/hagezi/dns-blocklists

**Comment by mchawk777** [comment]
Thanks for the quick response. 👍
Maybe the blocklisten.md (https://github.com/RPiList/specials/blob/master/Blocklisten.md) shold be editet.
I copied the links from it. 😉

**Comment by RPiList** [comment]
Lists have been removed until I figured out which one still work and which one are not working. Greetings.
